apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-helm-app-non-prod
  namespace: argocd
spec:
  destination:
    namespace: isd-argo-install
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/NaveenBalagouni/isd-enterprise-argo.git'
    path: apps-resources/single-helm-resource
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: non-prod-envoronment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
